### POST create user
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "displayName": "Test User",
  "username": "#123",
  "email": "test@example.com",
  "password": "123456"
}

### GET all Pins
GET http://localhost:3000/pins/
Accept: application/json
